#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : jemalloc
Version  : 5.2.1
Release  : 36
URL      : https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2
Source0  : https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2
Summary  : A general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: jemalloc-bin = %{version}-%{release}
Requires: jemalloc-lib = %{version}-%{release}
Requires: jemalloc-license = %{version}-%{release}

%description
jemalloc is a general purpose malloc(3) implementation that emphasizes
fragmentation avoidance and scalable concurrency support.  jemalloc first came
into use as the FreeBSD libc allocator in 2005, and since then it has found its
way into numerous applications that rely on its predictable behavior.  In 2010
jemalloc development efforts broadened to include developer support features
such as heap profiling and extensive monitoring/tuning hooks.  Modern jemalloc
releases continue to be integrated back into FreeBSD, and therefore versatility
remains critical.  Ongoing development efforts trend toward making jemalloc
among the best allocators for a broad range of demanding applications, and
eliminating/mitigating weaknesses that have practical repercussions for real
world applications.

%package bin
Summary: bin components for the jemalloc package.
Group: Binaries
Requires: jemalloc-license = %{version}-%{release}

%description bin
bin components for the jemalloc package.


%package dev
Summary: dev components for the jemalloc package.
Group: Development
Requires: jemalloc-lib = %{version}-%{release}
Requires: jemalloc-bin = %{version}-%{release}
Provides: jemalloc-devel = %{version}-%{release}
Requires: jemalloc = %{version}-%{release}

%description dev
dev components for the jemalloc package.


%package doc
Summary: doc components for the jemalloc package.
Group: Documentation

%description doc
doc components for the jemalloc package.


%package lib
Summary: lib components for the jemalloc package.
Group: Libraries
Requires: jemalloc-license = %{version}-%{release}

%description lib
lib components for the jemalloc package.


%package license
Summary: license components for the jemalloc package.
Group: Default

%description license
license components for the jemalloc package.


%package staticdev
Summary: staticdev components for the jemalloc package.
Group: Default
Requires: jemalloc-dev = %{version}-%{release}

%description staticdev
staticdev components for the jemalloc package.


%prep
%setup -q -n jemalloc-5.2.1
cd %{_builddir}/jemalloc-5.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579286588
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure  --disable-initial-exec-tls
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1579286588
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jemalloc
cp %{_builddir}/jemalloc-5.2.1/COPYING %{buildroot}/usr/share/package-licenses/jemalloc/c797cef3f1b13a960a5119a084fb88529a924fd7
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/pprof

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jemalloc-config
/usr/bin/jemalloc.sh
/usr/bin/jeprof

%files dev
%defattr(-,root,root,-)
/usr/include/jemalloc/jemalloc.h
/usr/lib64/libjemalloc.so
/usr/lib64/pkgconfig/jemalloc.pc
/usr/share/man/man3/jemalloc.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/jemalloc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjemalloc.so.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jemalloc/c797cef3f1b13a960a5119a084fb88529a924fd7

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libjemalloc.a
/usr/lib64/libjemalloc_pic.a
